import React from "react";

function CallWithPara() {
  const data = {
    token: null,
    availableFlights: [
      {
        itinerary: {
          flightKey: "FL_EVNBRU_2",
          avKey: "3F533_5F835",
          flightDirection: 1,
          connectionType: 2,
          noStops: 1,
          totalSegmentsWithStopOver: 2,
          segments: [
            {
              segmentKey: "SEG_EVNRMO_3",
              depCode: "EVN",
              arrCode: "RMO",
              carrierCode: "3F",
              mktAirlineCode: "3F",
              flightNumber: "533",
              depDateTime: "2024-07-09T01:00:00",
              arrDateTime: "2024-07-09T02:40:00",
              durationInMins: 160,
              oprAirlineCode: "3F",
              stopOverDurationInMins: 250,
              flightStatus: null,
              isScheduleChanged: false,
            },
            {
              segmentKey: "SEG_RMOBRU_4",
              depCode: "RMO",
              arrCode: "BRU",
              carrierCode: "5F",
              mktAirlineCode: "5F",
              flightNumber: "835",
              depDateTime: "2024-07-09T06:50:00",
              arrDateTime: "2024-07-09T09:10:00",
              durationInMins: 200,
              oprAirlineCode: "5F",
              stopOverDurationInMins: 0,
              flightStatus: null,
              isScheduleChanged: false,
            },
          ],
          isCheckInAvailable: false,
          isMMBAvail: false,
          isChangeFlightAllowed: false,
          isChangePaxAllowed: false,
          isExpired: false,
          isCheckOutAvailable: false,
          isCancelAllowed: false,
          isDownloadBPAvailable: false,
          isMultipleFOP: false,
          isDuePaymentAllowed: false,
          isSearchAncillaryAllowed: false,
          reasonCode: 0,
        },
        fareGroupInfo: [
          {
            flightOfferKey: "BO_1_FL_2_FG_1",
            majorCabin: null,
            flightKeyRefs: ["FL_EVNBRU_2"],
            currencyCode: "EUR",
            availableCount: 0,
            cabin: [
              {
                cabinClassCode: "ST",
                bookingClassCode: "A",
                fareBasisCode: "ASTDOW",
                segmentRefKey: "SEG_EVNRMO_3",
                availability: "",
              },
              {
                cabinClassCode: "ST",
                bookingClassCode: "J",
                fareBasisCode: "ASTDOW",
                segmentRefKey: "SEG_RMOBRU_4",
                availability: "",
              },
            ],
            priceInfo: {
              total: 260.0,
              perPaxPriceInfo: [
                {
                  paxType: "ADT",
                  paxKeyRef: null,
                  amount: 230.0,
                  tax: 30.0,
                },
              ],
              priceListInfo: [
                {
                  name: "BASEFARE",
                  priceType: "BASEFARE",
                  total: 230.0,
                  taxBreakDownInfo: null,
                  discountInfo: null,
                },
                {
                  name: "TAX",
                  priceType: "TAX",
                  total: 30.0,
                  taxBreakDownInfo: [
                    {
                      name: "",
                      taxCode: "",
                      amount: 30.0,
                    },
                  ],
                  discountInfo: null,
                },
                {
                  name: "DISCOUNT",
                  priceType: "DISCOUNT",
                  total: 10.0,
                  taxBreakDownInfo: null,
                  discountInfo: [
                    {
                      currency: "EUR",
                      totalDiscount: 5.0,
                      code: "CLUB",
                      discountType: "CLUB",
                      programCode: "FLY",
                      programLevel: "F1+",
                      paxType: "ADT",
                      applicableQty: 2,
                      feeDiscount: 0.0,
                      segmentRefKey: "SEG_EVNRMO_3",
                      perPaxDiscount: 5.0,
                    },
                    {
                      currency: "EUR",
                      totalDiscount: 5.0,
                      code: "CLUB",
                      discountType: "CLUB",
                      programCode: "FLY",
                      programLevel: "F1+",
                      paxType: "ADT",
                      applicableQty: 2,
                      feeDiscount: 0.0,
                      segmentRefKey: "SEG_RMOBRU_4",
                      perPaxDiscount: 5.0,
                    },
                  ],
                },
              ],
              cashbackPriceInfo: null,
            },
            bundleInfo: null,
          },
          {
            flightOfferKey: "BO_1_FL_2_FG_2",
            majorCabin: null,
            flightKeyRefs: ["FL_EVNBRU_2"],
            currencyCode: "EUR",
            availableCount: 0,
            cabin: [
              {
                cabinClassCode: "LO",
                bookingClassCode: "A",
                fareBasisCode: "ALOYOW",
                segmentRefKey: "SEG_EVNRMO_3",
                availability: "",
              },
              {
                cabinClassCode: "LO",
                bookingClassCode: "J",
                fareBasisCode: "ALOYOW",
                segmentRefKey: "SEG_RMOBRU_4",
                availability: "",
              },
            ],
            priceInfo: {
              total: 330.0,
              perPaxPriceInfo: [
                {
                  paxType: "ADT",
                  paxKeyRef: null,
                  amount: 300.0,
                  tax: 30.0,
                },
              ],
              priceListInfo: [
                {
                  name: "BASEFARE",
                  priceType: "BASEFARE",
                  total: 300.0,
                  taxBreakDownInfo: null,
                  discountInfo: null,
                },
                {
                  name: "TAX",
                  priceType: "TAX",
                  total: 30.0,
                  taxBreakDownInfo: [
                    {
                      name: "",
                      taxCode: "",
                      amount: 30.0,
                    },
                  ],
                  discountInfo: null,
                },
                {
                  name: "DISCOUNT",
                  priceType: "DISCOUNT",
                  total: 10.0,
                  taxBreakDownInfo: null,
                  discountInfo: [
                    {
                      currency: "EUR",
                      totalDiscount: 5.0,
                      code: "CLUB",
                      discountType: "CLUB",
                      programCode: "FLY",
                      programLevel: "F1+",
                      paxType: "ADT",
                      applicableQty: 2,
                      feeDiscount: 0.0,
                      segmentRefKey: "SEG_EVNRMO_3",
                      perPaxDiscount: 5.0,
                    },
                    {
                      currency: "EUR",
                      totalDiscount: 5.0,
                      code: "CLUB",
                      discountType: "CLUB",
                      programCode: "FLY",
                      programLevel: "F1+",
                      paxType: "ADT",
                      applicableQty: 2,
                      feeDiscount: 0.0,
                      segmentRefKey: "SEG_RMOBRU_4",
                      perPaxDiscount: 5.0,
                    },
                  ],
                },
              ],
              cashbackPriceInfo: [
                {
                  cashbackPercent: 5.0,
                  cashbackPrice: 16.5,
                  currency: "EUR",
                },
              ],
            },
            bundleInfo: null,
          },
          {
            flightOfferKey: "BO_1_FL_2_FG_3",
            majorCabin: null,
            flightKeyRefs: ["FL_EVNBRU_2"],
            currencyCode: "EUR",
            availableCount: 0,
            cabin: [
              {
                cabinClassCode: "AD",
                bookingClassCode: "A",
                fareBasisCode: "AADVOW",
                segmentRefKey: "SEG_EVNRMO_3",
                availability: "",
              },
              {
                cabinClassCode: "AD",
                bookingClassCode: "J",
                fareBasisCode: "AADVOW",
                segmentRefKey: "SEG_RMOBRU_4",
                availability: "",
              },
            ],
            priceInfo: {
              total: 420.0,
              perPaxPriceInfo: [
                {
                  paxType: "ADT",
                  paxKeyRef: null,
                  amount: 390.0,
                  tax: 30.0,
                },
              ],
              priceListInfo: [
                {
                  name: "BASEFARE",
                  priceType: "BASEFARE",
                  total: 390.0,
                  taxBreakDownInfo: null,
                  discountInfo: null,
                },
                {
                  name: "TAX",
                  priceType: "TAX",
                  total: 30.0,
                  taxBreakDownInfo: [
                    {
                      name: "",
                      taxCode: "",
                      amount: 30.0,
                    },
                  ],
                  discountInfo: null,
                },
                {
                  name: "DISCOUNT",
                  priceType: "DISCOUNT",
                  total: 10.0,
                  taxBreakDownInfo: null,
                  discountInfo: [
                    {
                      currency: "EUR",
                      totalDiscount: 5.0,
                      code: "CLUB",
                      discountType: "CLUB",
                      programCode: "FLY",
                      programLevel: "F1+",
                      paxType: "ADT",
                      applicableQty: 2,
                      feeDiscount: 0.0,
                      segmentRefKey: "SEG_EVNRMO_3",
                      perPaxDiscount: 5.0,
                    },
                    {
                      currency: "EUR",
                      totalDiscount: 5.0,
                      code: "CLUB",
                      discountType: "CLUB",
                      programCode: "FLY",
                      programLevel: "F1+",
                      paxType: "ADT",
                      applicableQty: 2,
                      feeDiscount: 0.0,
                      segmentRefKey: "SEG_RMOBRU_4",
                      perPaxDiscount: 5.0,
                    },
                  ],
                },
              ],
              cashbackPriceInfo: [
                {
                  cashbackPercent: 7.0,
                  cashbackPrice: 29.4,
                  currency: "EUR",
                },
              ],
            },
            bundleInfo: [
              {
                bundleKey: null,
                bundleCode: "ADV",
                bundleType: "INCLUDED",
                bundles: [
                  {
                    paxType: null,
                    bundleSSR: [
                      {
                        ssrCode: "CKE",
                        ssrType: null,
                        price: 0.0,
                        tax: 0.0,
                        isAvailable: true,
                      },
                    ],
                    totalPrice: 0.0,
                    totalTax: 0.0,
                  },
                  {
                    paxType: null,
                    bundleSSR: [
                      {
                        ssrCode: "PRTP",
                        ssrType: null,
                        price: 0.0,
                        tax: 0.0,
                        isAvailable: true,
                      },
                    ],
                    totalPrice: 0.0,
                    totalTax: 0.0,
                  },
                  {
                    paxType: null,
                    bundleSSR: [
                      {
                        ssrCode: "SMB1",
                        ssrType: null,
                        price: 0.0,
                        tax: 0.0,
                        isAvailable: true,
                      },
                    ],
                    totalPrice: 0.0,
                    totalTax: 0.0,
                  },
                  {
                    paxType: null,
                    bundleSSR: [
                      {
                        ssrCode: "FLEX",
                        ssrType: null,
                        price: 0.0,
                        tax: 0.0,
                        isAvailable: true,
                      },
                    ],
                    totalPrice: 0.0,
                    totalTax: 0.0,
                  },
                  {
                    paxType: null,
                    bundleSSR: [
                      {
                        ssrCode: "BPPP",
                        ssrType: null,
                        price: 0.0,
                        tax: 0.0,
                        isAvailable: true,
                      },
                    ],
                    totalPrice: 0.0,
                    totalTax: 0.0,
                  },
                  {
                    paxType: null,
                    bundleSSR: [
                      {
                        ssrCode: "STB1",
                        ssrType: null,
                        price: 0.0,
                        tax: 0.0,
                        isAvailable: true,
                      },
                    ],
                    totalPrice: 0.0,
                    totalTax: 0.0,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        itinerary: {
          flightKey: "FL_BRUEVN_4",
          avKey: "5F836_3F868",
          flightDirection: 2,
          connectionType: 2,
          noStops: 1,
          totalSegmentsWithStopOver: 2,
          segments: [
            {
              segmentKey: "SEG_BRURMO_7",
              depCode: "BRU",
              arrCode: "RMO",
              carrierCode: "5F",
              mktAirlineCode: "5F",
              flightNumber: "836",
              depDateTime: "2024-08-20T10:10:00",
              arrDateTime: "2024-08-20T14:10:00",
              durationInMins: 180,
              oprAirlineCode: "5F",
              stopOverDurationInMins: 210,
              flightStatus: null,
              isScheduleChanged: false,
            },
            {
              segmentKey: "SEG_RMOEVN_8",
              depCode: "RMO",
              arrCode: "EVN",
              carrierCode: "3F",
              mktAirlineCode: "3F",
              flightNumber: "868",
              depDateTime: "2024-08-20T17:40:00",
              arrDateTime: "2024-08-20T21:10:00",
              durationInMins: 150,
              oprAirlineCode: "3F",
              stopOverDurationInMins: 0,
              flightStatus: null,
              isScheduleChanged: false,
            },
          ],
          isCheckInAvailable: false,
          isMMBAvail: false,
          isChangeFlightAllowed: false,
          isChangePaxAllowed: false,
          isExpired: false,
          isCheckOutAvailable: false,
          isCancelAllowed: false,
          isDownloadBPAvailable: false,
          isMultipleFOP: false,
          isDuePaymentAllowed: false,
          isSearchAncillaryAllowed: false,
          reasonCode: 0,
        },
        fareGroupInfo: [
          {
            flightOfferKey: "BO_2_FL_4_FG_1",
            majorCabin: null,
            flightKeyRefs: ["FL_BRUEVN_4"],
            currencyCode: "EUR",
            availableCount: 3,
            cabin: [
              {
                cabinClassCode: "ST",
                bookingClassCode: "Q",
                fareBasisCode: "QSTDOW",
                segmentRefKey: "SEG_BRURMO_7",
                availability: "3",
              },
              {
                cabinClassCode: "ST",
                bookingClassCode: "A",
                fareBasisCode: "QSTDOW",
                segmentRefKey: "SEG_RMOEVN_8",
                availability: "3",
              },
            ],
            priceInfo: {
              total: 300.0,
              perPaxPriceInfo: [
                {
                  paxType: "ADT",
                  paxKeyRef: null,
                  amount: 270.0,
                  tax: 30.0,
                },
              ],
              priceListInfo: [
                {
                  name: "BASEFARE",
                  priceType: "BASEFARE",
                  total: 270.0,
                  taxBreakDownInfo: null,
                  discountInfo: null,
                },
                {
                  name: "TAX",
                  priceType: "TAX",
                  total: 30.0,
                  taxBreakDownInfo: [
                    {
                      name: "",
                      taxCode: "",
                      amount: 30.0,
                    },
                  ],
                  discountInfo: null,
                },
                {
                  name: "DISCOUNT",
                  priceType: "DISCOUNT",
                  total: 10.0,
                  taxBreakDownInfo: null,
                  discountInfo: [
                    {
                      currency: "EUR",
                      totalDiscount: 5.0,
                      code: "CLUB",
                      discountType: "CLUB",
                      programCode: "FLY",
                      programLevel: "F1+",
                      paxType: "ADT",
                      applicableQty: 2,
                      feeDiscount: 0.0,
                      segmentRefKey: "SEG_BRURMO_7",
                      perPaxDiscount: 5.0,
                    },
                    {
                      currency: "EUR",
                      totalDiscount: 5.0,
                      code: "CLUB",
                      discountType: "CLUB",
                      programCode: "FLY",
                      programLevel: "F1+",
                      paxType: "ADT",
                      applicableQty: 2,
                      feeDiscount: 0.0,
                      segmentRefKey: "SEG_RMOEVN_8",
                      perPaxDiscount: 5.0,
                    },
                  ],
                },
              ],
              cashbackPriceInfo: null,
            },
            bundleInfo: null,
          },
          {
            flightOfferKey: "BO_2_FL_4_FG_2",
            majorCabin: null,
            flightKeyRefs: ["FL_BRUEVN_4"],
            currencyCode: "EUR",
            availableCount: 3,
            cabin: [
              {
                cabinClassCode: "LO",
                bookingClassCode: "Q",
                fareBasisCode: "QLOYOW",
                segmentRefKey: "SEG_BRURMO_7",
                availability: "3",
              },
              {
                cabinClassCode: "LO",
                bookingClassCode: "A",
                fareBasisCode: "QLOYOW",
                segmentRefKey: "SEG_RMOEVN_8",
                availability: "3",
              },
            ],
            priceInfo: {
              total: 370.0,
              perPaxPriceInfo: [
                {
                  paxType: "ADT",
                  paxKeyRef: null,
                  amount: 340.0,
                  tax: 30.0,
                },
              ],
              priceListInfo: [
                {
                  name: "BASEFARE",
                  priceType: "BASEFARE",
                  total: 340.0,
                  taxBreakDownInfo: null,
                  discountInfo: null,
                },
                {
                  name: "TAX",
                  priceType: "TAX",
                  total: 30.0,
                  taxBreakDownInfo: [
                    {
                      name: "",
                      taxCode: "",
                      amount: 30.0,
                    },
                  ],
                  discountInfo: null,
                },
                {
                  name: "DISCOUNT",
                  priceType: "DISCOUNT",
                  total: 10.0,
                  taxBreakDownInfo: null,
                  discountInfo: [
                    {
                      currency: "EUR",
                      totalDiscount: 5.0,
                      code: "CLUB",
                      discountType: "CLUB",
                      programCode: "FLY",
                      programLevel: "F1+",
                      paxType: "ADT",
                      applicableQty: 2,
                      feeDiscount: 0.0,
                      segmentRefKey: "SEG_BRURMO_7",
                      perPaxDiscount: 5.0,
                    },
                    {
                      currency: "EUR",
                      totalDiscount: 5.0,
                      code: "CLUB",
                      discountType: "CLUB",
                      programCode: "FLY",
                      programLevel: "F1+",
                      paxType: "ADT",
                      applicableQty: 2,
                      feeDiscount: 0.0,
                      segmentRefKey: "SEG_RMOEVN_8",
                      perPaxDiscount: 5.0,
                    },
                  ],
                },
              ],
              cashbackPriceInfo: [
                {
                  cashbackPercent: 5.0,
                  cashbackPrice: 18.5,
                  currency: "EUR",
                },
              ],
            },
            bundleInfo: null,
          },
          {
            flightOfferKey: "BO_2_FL_4_FG_3",
            majorCabin: null,
            flightKeyRefs: ["FL_BRUEVN_4"],
            currencyCode: "EUR",
            availableCount: 3,
            cabin: [
              {
                cabinClassCode: "AD",
                bookingClassCode: "Q",
                fareBasisCode: "QADVOW",
                segmentRefKey: "SEG_BRURMO_7",
                availability: "3",
              },
              {
                cabinClassCode: "AD",
                bookingClassCode: "A",
                fareBasisCode: "QADVOW",
                segmentRefKey: "SEG_RMOEVN_8",
                availability: "3",
              },
            ],
            priceInfo: {
              total: 460.0,
              perPaxPriceInfo: [
                {
                  paxType: "ADT",
                  paxKeyRef: null,
                  amount: 430.0,
                  tax: 30.0,
                },
              ],
              priceListInfo: [
                {
                  name: "BASEFARE",
                  priceType: "BASEFARE",
                  total: 430.0,
                  taxBreakDownInfo: null,
                  discountInfo: null,
                },
                {
                  name: "TAX",
                  priceType: "TAX",
                  total: 30.0,
                  taxBreakDownInfo: [
                    {
                      name: "",
                      taxCode: "",
                      amount: 30.0,
                    },
                  ],
                  discountInfo: null,
                },
                {
                  name: "DISCOUNT",
                  priceType: "DISCOUNT",
                  total: 10.0,
                  taxBreakDownInfo: null,
                  discountInfo: [
                    {
                      currency: "EUR",
                      totalDiscount: 5.0,
                      code: "CLUB",
                      discountType: "CLUB",
                      programCode: "FLY",
                      programLevel: "F1+",
                      paxType: "ADT",
                      applicableQty: 2,
                      feeDiscount: 0.0,
                      segmentRefKey: "SEG_BRURMO_7",
                      perPaxDiscount: 5.0,
                    },
                    {
                      currency: "EUR",
                      totalDiscount: 5.0,
                      code: "CLUB",
                      discountType: "CLUB",
                      programCode: "FLY",
                      programLevel: "F1+",
                      paxType: "ADT",
                      applicableQty: 2,
                      feeDiscount: 0.0,
                      segmentRefKey: "SEG_RMOEVN_8",
                      perPaxDiscount: 5.0,
                    },
                  ],
                },
              ],
              cashbackPriceInfo: [
                {
                  cashbackPercent: 7.0,
                  cashbackPrice: 32.2,
                  currency: "EUR",
                },
              ],
            },
            bundleInfo: [
              {
                bundleKey: null,
                bundleCode: "ADV",
                bundleType: "INCLUDED",
                bundles: [
                  {
                    paxType: null,
                    bundleSSR: [
                      {
                        ssrCode: "CKE",
                        ssrType: null,
                        price: 0.0,
                        tax: 0.0,
                        isAvailable: true,
                      },
                    ],
                    totalPrice: 0.0,
                    totalTax: 0.0,
                  },
                  {
                    paxType: null,
                    bundleSSR: [
                      {
                        ssrCode: "PRTP",
                        ssrType: null,
                        price: 0.0,
                        tax: 0.0,
                        isAvailable: true,
                      },
                    ],
                    totalPrice: 0.0,
                    totalTax: 0.0,
                  },
                  {
                    paxType: null,
                    bundleSSR: [
                      {
                        ssrCode: "SMB1",
                        ssrType: null,
                        price: 0.0,
                        tax: 0.0,
                        isAvailable: true,
                      },
                    ],
                    totalPrice: 0.0,
                    totalTax: 0.0,
                  },
                  {
                    paxType: null,
                    bundleSSR: [
                      {
                        ssrCode: "FLEX",
                        ssrType: null,
                        price: 0.0,
                        tax: 0.0,
                        isAvailable: true,
                      },
                    ],
                    totalPrice: 0.0,
                    totalTax: 0.0,
                  },
                  {
                    paxType: null,
                    bundleSSR: [
                      {
                        ssrCode: "BPPP",
                        ssrType: null,
                        price: 0.0,
                        tax: 0.0,
                        isAvailable: true,
                      },
                    ],
                    totalPrice: 0.0,
                    totalTax: 0.0,
                  },
                  {
                    paxType: null,
                    bundleSSR: [
                      {
                        ssrCode: "STB1",
                        ssrType: null,
                        price: 0.0,
                        tax: 0.0,
                        isAvailable: true,
                      },
                    ],
                    totalPrice: 0.0,
                    totalTax: 0.0,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        itinerary: {
          flightKey: "FL_BRUEVN_3",
          avKey: "5F836_3F534",
          flightDirection: 2,
          connectionType: 2,
          noStops: 1,
          totalSegmentsWithStopOver: 2,
          segments: [
            {
              segmentKey: "SEG_BRURMO_5",
              depCode: "BRU",
              arrCode: "RMO",
              carrierCode: "5F",
              mktAirlineCode: "5F",
              flightNumber: "836",
              depDateTime: "2024-08-20T10:10:00",
              arrDateTime: "2024-08-20T14:10:00",
              durationInMins: 180,
              oprAirlineCode: "5F",
              stopOverDurationInMins: 810,
              flightStatus: null,
              isScheduleChanged: false,
            },
            {
              segmentKey: "SEG_RMOEVN_6",
              depCode: "RMO",
              arrCode: "EVN",
              carrierCode: "3F",
              mktAirlineCode: "3F",
              flightNumber: "534",
              depDateTime: "2024-08-21T03:40:00",
              arrDateTime: "2024-08-21T07:10:00",
              durationInMins: 150,
              oprAirlineCode: "3F",
              stopOverDurationInMins: 0,
              flightStatus: null,
              isScheduleChanged: false,
            },
          ],
          isCheckInAvailable: false,
          isMMBAvail: false,
          isChangeFlightAllowed: false,
          isChangePaxAllowed: false,
          isExpired: false,
          isCheckOutAvailable: false,
          isCancelAllowed: false,
          isDownloadBPAvailable: false,
          isMultipleFOP: false,
          isDuePaymentAllowed: false,
          isSearchAncillaryAllowed: false,
          reasonCode: 0,
        },
        fareGroupInfo: [
          {
            flightOfferKey: "BO_2_FL_3_FG_1",
            majorCabin: null,
            flightKeyRefs: ["FL_BRUEVN_3"],
            currencyCode: "EUR",
            availableCount: 3,
            cabin: [
              {
                cabinClassCode: "ST",
                bookingClassCode: "Q",
                fareBasisCode: "QSTDOW",
                segmentRefKey: "SEG_BRURMO_5",
                availability: "3",
              },
              {
                cabinClassCode: "ST",
                bookingClassCode: "B",
                fareBasisCode: "QSTDOW",
                segmentRefKey: "SEG_RMOEVN_6",
                availability: "3",
              },
            ],
            priceInfo: {
              total: 290.0,
              perPaxPriceInfo: [
                {
                  paxType: "ADT",
                  paxKeyRef: null,
                  amount: 260.0,
                  tax: 30.0,
                },
              ],
              priceListInfo: [
                {
                  name: "BASEFARE",
                  priceType: "BASEFARE",
                  total: 260.0,
                  taxBreakDownInfo: null,
                  discountInfo: null,
                },
                {
                  name: "TAX",
                  priceType: "TAX",
                  total: 30.0,
                  taxBreakDownInfo: [
                    {
                      name: "",
                      taxCode: "",
                      amount: 30.0,
                    },
                  ],
                  discountInfo: null,
                },
                {
                  name: "DISCOUNT",
                  priceType: "DISCOUNT",
                  total: 10.0,
                  taxBreakDownInfo: null,
                  discountInfo: [
                    {
                      currency: "EUR",
                      totalDiscount: 5.0,
                      code: "CLUB",
                      discountType: "CLUB",
                      programCode: "FLY",
                      programLevel: "F1+",
                      paxType: "ADT",
                      applicableQty: 2,
                      feeDiscount: 0.0,
                      segmentRefKey: "SEG_BRURMO_5",
                      perPaxDiscount: 5.0,
                    },
                    {
                      currency: "EUR",
                      totalDiscount: 5.0,
                      code: "CLUB",
                      discountType: "CLUB",
                      programCode: "FLY",
                      programLevel: "F1+",
                      paxType: "ADT",
                      applicableQty: 2,
                      feeDiscount: 0.0,
                      segmentRefKey: "SEG_RMOEVN_6",
                      perPaxDiscount: 5.0,
                    },
                  ],
                },
              ],
              cashbackPriceInfo: null,
            },
            bundleInfo: null,
          },
          {
            flightOfferKey: "BO_2_FL_3_FG_2",
            majorCabin: null,
            flightKeyRefs: ["FL_BRUEVN_3"],
            currencyCode: "EUR",
            availableCount: 3,
            cabin: [
              {
                cabinClassCode: "LO",
                bookingClassCode: "Q",
                fareBasisCode: "QLOYOW",
                segmentRefKey: "SEG_BRURMO_5",
                availability: "3",
              },
              {
                cabinClassCode: "LO",
                bookingClassCode: "B",
                fareBasisCode: "QLOYOW",
                segmentRefKey: "SEG_RMOEVN_6",
                availability: "3",
              },
            ],
            priceInfo: {
              total: 360.0,
              perPaxPriceInfo: [
                {
                  paxType: "ADT",
                  paxKeyRef: null,
                  amount: 330.0,
                  tax: 30.0,
                },
              ],
              priceListInfo: [
                {
                  name: "BASEFARE",
                  priceType: "BASEFARE",
                  total: 330.0,
                  taxBreakDownInfo: null,
                  discountInfo: null,
                },
                {
                  name: "TAX",
                  priceType: "TAX",
                  total: 30.0,
                  taxBreakDownInfo: [
                    {
                      name: "",
                      taxCode: "",
                      amount: 30.0,
                    },
                  ],
                  discountInfo: null,
                },
                {
                  name: "DISCOUNT",
                  priceType: "DISCOUNT",
                  total: 10.0,
                  taxBreakDownInfo: null,
                  discountInfo: [
                    {
                      currency: "EUR",
                      totalDiscount: 5.0,
                      code: "CLUB",
                      discountType: "CLUB",
                      programCode: "FLY",
                      programLevel: "F1+",
                      paxType: "ADT",
                      applicableQty: 2,
                      feeDiscount: 0.0,
                      segmentRefKey: "SEG_BRURMO_5",
                      perPaxDiscount: 5.0,
                    },
                    {
                      currency: "EUR",
                      totalDiscount: 5.0,
                      code: "CLUB",
                      discountType: "CLUB",
                      programCode: "FLY",
                      programLevel: "F1+",
                      paxType: "ADT",
                      applicableQty: 2,
                      feeDiscount: 0.0,
                      segmentRefKey: "SEG_RMOEVN_6",
                      perPaxDiscount: 5.0,
                    },
                  ],
                },
              ],
              cashbackPriceInfo: [
                {
                  cashbackPercent: 5.0,
                  cashbackPrice: 18.0,
                  currency: "EUR",
                },
              ],
            },
            bundleInfo: null,
          },
          {
            flightOfferKey: "BO_2_FL_3_FG_3",
            majorCabin: null,
            flightKeyRefs: ["FL_BRUEVN_3"],
            currencyCode: "EUR",
            availableCount: 3,
            cabin: [
              {
                cabinClassCode: "AD",
                bookingClassCode: "Q",
                fareBasisCode: "QADVOW",
                segmentRefKey: "SEG_BRURMO_5",
                availability: "3",
              },
              {
                cabinClassCode: "AD",
                bookingClassCode: "B",
                fareBasisCode: "QADVOW",
                segmentRefKey: "SEG_RMOEVN_6",
                availability: "3",
              },
            ],
            priceInfo: {
              total: 450.0,
              perPaxPriceInfo: [
                {
                  paxType: "ADT",
                  paxKeyRef: null,
                  amount: 420.0,
                  tax: 30.0,
                },
              ],
              priceListInfo: [
                {
                  name: "BASEFARE",
                  priceType: "BASEFARE",
                  total: 420.0,
                  taxBreakDownInfo: null,
                  discountInfo: null,
                },
                {
                  name: "TAX",
                  priceType: "TAX",
                  total: 30.0,
                  taxBreakDownInfo: [
                    {
                      name: "",
                      taxCode: "",
                      amount: 30.0,
                    },
                  ],
                  discountInfo: null,
                },
                {
                  name: "DISCOUNT",
                  priceType: "DISCOUNT",
                  total: 10.0,
                  taxBreakDownInfo: null,
                  discountInfo: [
                    {
                      currency: "EUR",
                      totalDiscount: 5.0,
                      code: "CLUB",
                      discountType: "CLUB",
                      programCode: "FLY",
                      programLevel: "F1+",
                      paxType: "ADT",
                      applicableQty: 2,
                      feeDiscount: 0.0,
                      segmentRefKey: "SEG_BRURMO_5",
                      perPaxDiscount: 5.0,
                    },
                    {
                      currency: "EUR",
                      totalDiscount: 5.0,
                      code: "CLUB",
                      discountType: "CLUB",
                      programCode: "FLY",
                      programLevel: "F1+",
                      paxType: "ADT",
                      applicableQty: 2,
                      feeDiscount: 0.0,
                      segmentRefKey: "SEG_RMOEVN_6",
                      perPaxDiscount: 5.0,
                    },
                  ],
                },
              ],
              cashbackPriceInfo: [
                {
                  cashbackPercent: 7.0,
                  cashbackPrice: 31.5,
                  currency: "EUR",
                },
              ],
            },
            bundleInfo: [
              {
                bundleKey: null,
                bundleCode: "ADV",
                bundleType: "INCLUDED",
                bundles: [
                  {
                    paxType: null,
                    bundleSSR: [
                      {
                        ssrCode: "CKE",
                        ssrType: null,
                        price: 0.0,
                        tax: 0.0,
                        isAvailable: true,
                      },
                    ],
                    totalPrice: 0.0,
                    totalTax: 0.0,
                  },
                  {
                    paxType: null,
                    bundleSSR: [
                      {
                        ssrCode: "PRTP",
                        ssrType: null,
                        price: 0.0,
                        tax: 0.0,
                        isAvailable: true,
                      },
                    ],
                    totalPrice: 0.0,
                    totalTax: 0.0,
                  },
                  {
                    paxType: null,
                    bundleSSR: [
                      {
                        ssrCode: "SMB1",
                        ssrType: null,
                        price: 0.0,
                        tax: 0.0,
                        isAvailable: true,
                      },
                    ],
                    totalPrice: 0.0,
                    totalTax: 0.0,
                  },
                  {
                    paxType: null,
                    bundleSSR: [
                      {
                        ssrCode: "FLEX",
                        ssrType: null,
                        price: 0.0,
                        tax: 0.0,
                        isAvailable: true,
                      },
                    ],
                    totalPrice: 0.0,
                    totalTax: 0.0,
                  },
                  {
                    paxType: null,
                    bundleSSR: [
                      {
                        ssrCode: "BPPP",
                        ssrType: null,
                        price: 0.0,
                        tax: 0.0,
                        isAvailable: true,
                      },
                    ],
                    totalPrice: 0.0,
                    totalTax: 0.0,
                  },
                  {
                    paxType: null,
                    bundleSSR: [
                      {
                        ssrCode: "STB1",
                        ssrType: null,
                        price: 0.0,
                        tax: 0.0,
                        isAvailable: true,
                      },
                    ],
                    totalPrice: 0.0,
                    totalTax: 0.0,
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
    result: {
      isSuccess: true,
      msgs: null,
    },
  };
  return <div>CallWithPara</div>;
}

export default CallWithPara;
